# Generated by Django 5.1.6 on 2025-05-15 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('clinical_event', models.CharField(blank=True, choices=[('CAR', 'Cardiac arrest resuscitated'), ('AR', 'Arrhytmia'), ('CT', 'Cardiac transplant'), ('DEATH', 'Death'), ('OT', 'Other'), ('STROKE', 'Stroke')], default='', max_length=100)),
                ('cause', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_event', to='kokoro.patientprofile')),
            ],
        ),
    ]
