# Generated by Django 5.1.6 on 2025-05-13 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genetic_profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FIN_progressive_genetics', models.PositiveIntegerField(blank=True, null=True)),
                ('FIN_number', models.CharField(max_length=100)),
                ('PIN_number', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kokoro.patientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
