# Generated by Django 5.1.6 on 2025-05-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='company',
            field=models.CharField(blank=True, choices=[('AB', 'Abbott'), ('BT', 'Biotronik'), ('MT', 'Medtronic'), ('BS', 'Boston'), ('SJ', 'St. Jude')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='type',
            field=models.CharField(blank=True, choices=[('CD', 'Cardiac Device'), ('LR', 'Loop Recorder'), ('PM', 'Pace Maker')], default='', max_length=5),
        ),
    ]
