# Generated by Django 5.1.6 on 2025-04-23 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imtc_id', models.CharField(max_length=20)),
                ('procedure_type', models.CharField(blank=True, choices=[('A', 'Ablation'), ('PA', 'Post-ablation follow-up'), ('DG', 'Diagnosis')], default='', max_length=2)),
                ('informed_consent', models.CharField(max_length=20)),
                ('collection_date', models.DateField()),
                ('pbmc_vials_n', models.PositiveIntegerField(blank=True, null=True)),
                ('pellet_vials_n', models.PositiveIntegerField(blank=True, null=True)),
                ('rna_vials_n', models.PositiveIntegerField(blank=True, null=True)),
                ('plasma_cold_vials_n', models.PositiveIntegerField(blank=True, null=True)),
                ('plasma_ambient_vials_n', models.PositiveIntegerField(blank=True, null=True)),
                ('rin', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='kokoro.patient_profile')),
            ],
        ),
    ]
