# Generated by Django 5.1.6 on 2025-05-14 08:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0002_genetic_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genetic_status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_status', models.CharField(choices=[('Proband', 'Proband'), ('Familiar', 'Familiar')], default='', max_length=100)),
                ('brs_family_members', models.PositiveIntegerField(blank=True, null=True)),
                ('family_brs', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3)),
                ('sd_family_members', models.PositiveIntegerField(blank=True, null=True)),
                ('family_lqts', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3)),
                ('lqts_family_members', models.PositiveIntegerField(blank=True, null=True)),
                ('family_er', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3)),
                ('er_family_members', models.PositiveIntegerField(blank=True, null=True)),
                ('family_cardiomiopathy', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3)),
                ('cardiomiopathy_family_members', models.PositiveIntegerField(blank=True, null=True)),
                ('sd_family_degree', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Grand-father', 'Grand-father'), ('Grand-mother', 'Grand-mother')], default='', max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kokoro.patientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genetic_test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_date', models.DateField()),
                ('test_category', models.CharField(choices=[('Oncology', 'Oncology'), ('Channellopathies', 'Channellopathies'), ('Cardiomiopathies', 'Cardiomiopathies'), ('Neuromuscolar dystrophies', 'Nd'), ('Collagenopathies', 'Collagenopathies'), ('Coagulopathies', 'Coagulopathies'), ('Syndromes / Dysmorphisms', 'Syndromes / Dysmorphisms'), ('Metabolic', 'Metabolic'), ('Screening', 'Screening'), ('Breast K', 'Breast K'), ('Nephropathy', 'Nephropathy'), ('Neuropathy', 'Neuropathy'), ('Hematopathy', 'Hematopathy'), ('Arrhythmias', 'Arrhythmias')], default='', max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kokoro.patientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
