# Generated by Django 5.1.6 on 2025-04-24 09:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0002_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('CD', 'Cardiac Device'), ('LR', 'Loop Recorder'), ('PM', 'Pace Maker')], default='', max_length=2)),
                ('company', models.CharField(blank=True, choices=[('AB', 'Abbott'), ('BT', 'Biotronik'), ('MT', 'Medtronic'), ('BS', 'Boston'), ('SJ', 'St. Jude')], default='', max_length=2)),
                ('model', models.CharField(blank=True, choices=[('INTICA 7 HF-TQPDF4/IS4', 'In7F4Is4'), ('RIVACOR 7 HF-T QP', 'Ri7Hfqp'), ('INTICA 7 HF-TQPDF1/IS4', 'In7Hfis4'), ('INTICA NEO 7 HF-T QP', 'Inn7Hfqp')], default='', max_length=50)),
                ('design', models.CharField(blank=True, choices=[('Single\\Dual Pacemaker', 'Sd Pacemaker'), ('Single\\Dual Chamber ICD', 'Sd Chamber Icd'), ('Other', 'Other')], default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ablation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_area', models.FloatField(blank=True, null=True)),
                ('bas_area_a_160', models.FloatField(blank=True, null=True)),
                ('bas_area_a_180', models.FloatField(blank=True, null=True)),
                ('bas_area_a_200', models.FloatField(blank=True, null=True)),
                ('basal_pdm', models.FloatField(blank=True, null=True)),
                ('total_rf_time', models.FloatField(blank=True, null=True)),
                ('rf_w', models.FloatField(blank=True, null=True)),
                ('complication', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=2)),
                ('complication_type', models.CharField(max_length=250)),
                ('therapy', models.CharField(max_length=250)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kokoro.PatientProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device_Implant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('lv4_ring', models.FloatField(blank=True, null=True)),
                ('lv3_ring', models.FloatField(blank=True, null=True)),
                ('lv2_ring', models.FloatField(blank=True, null=True)),
                ('lv1_tip', models.FloatField(blank=True, null=True)),
                ('v1', models.FloatField(blank=True, null=True)),
                ('ms1', models.PositiveIntegerField(blank=True, null=True)),
                ('lv_pulse_configuration_2_lv2', models.FloatField(blank=True, null=True)),
                ('pacing_impendance1', models.FloatField(blank=True, null=True)),
                ('v2', models.FloatField(blank=True, null=True)),
                ('ms2', models.PositiveIntegerField(blank=True, null=True)),
                ('pacing_impendance2', models.FloatField(blank=True, null=True)),
                ('v3', models.FloatField(blank=True, null=True)),
                ('ms3', models.PositiveIntegerField(blank=True, null=True)),
                ('pacing_impendance3', models.FloatField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kokoro.PatientProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(help_text='Unique identifier printed on the device', max_length=100, unique=True)),
                ('implantation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='kokoro.device_implant')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='kokoro.PatientProfile')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device', to='kokoro.devicetype')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('n_icd_shock_appropriate_pre_rf', models.PositiveIntegerField(blank=True, null=True)),
                ('n_icd_shock_inappropriate_pre_rf', models.PositiveIntegerField(blank=True, null=True)),
                ('inappropriate_pre_rf_shock_cause', models.CharField(blank=True, choices=[('TSPV', 'TPSV'), ('FA', 'FA'), ('LEMA', 'Malfunzionamento elettrocatetere vd'), ('FLU', 'Flutter Atriale'), ('MAC', 'Macrodislocazione Elettrocatetere'), ('SIN', 'Tachicardia Sinusale'), ('N', 'Rumore'), ('AB', "Bolla d'aria"), ('DIS', 'Dislocazione elettrodo VD'), ('TD', 'T double counting'), ('TVTF', 'TV>FV'), ('UNK', 'Sconosciuto')], default='', max_length=4)),
                ('n_icd_shock_appropriate_post_brs_diagnosis', models.PositiveIntegerField(blank=True, null=True)),
                ('inappropriate_post_brs_shock_cause', models.CharField(blank=True, choices=[('TSPV', 'TPSV'), ('FA', 'FA'), ('LEMA', 'Malfunzionamento elettrocatetere vd'), ('FLU', 'Flutter Atriale'), ('MAC', 'Macrodislocazione Elettrocatetere'), ('SIN', 'Tachicardia Sinusale'), ('N', 'Rumore'), ('AB', "Bolla d'aria"), ('DIS', 'Dislocazione elettrodo VD'), ('TD', 'T double counting'), ('TVTF', 'TV>FV'), ('UNK', 'Sconosciuto')], default='', max_length=4)),
                ('complications', models.CharField(blank=True, default='', max_length=250)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='kokoro.deviceinstance')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
