# Generated by Django 5.1.6 on 2025-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0002_alter_devicetype_company_alter_devicetype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='company',
            field=models.CharField(blank=True, choices=[('AB', 'Abbott'), ('BT', 'Biotronik'), ('MT', 'Medtronic'), ('BS', 'Boston'), ('SJ', 'St. Jude')], default='', max_length=50),
        ),
    ]
