# Generated by Django 5.1.6 on 2025-05-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0003_genetic_status_genetic_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genetic_test',
            old_name='consent_date',
            new_name='Consent_date',
        ),
    ]
