# Generated by Django 5.1.6 on 2025-04-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0003_devicetype_ablation_device_implant_deviceinstance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device_Implant',
            new_name='DeviceImplant',
        ),
        migrations.RenameModel(
            old_name='Patient_profile',
            new_name='PatientProfile',
        ),
    ]
