# Generated by Django 5.1.6 on 2025-05-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0003_alter_devicetype_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ablation',
            options={'verbose_name': 'Ablation', 'verbose_name_plural': 'Ablations'},
        ),
        migrations.AlterModelOptions(
            name='adrenaline_test',
            options={'verbose_name': 'Adrenaline test', 'verbose_name_plural': 'Adrenaline tests'},
        ),
        migrations.AlterModelOptions(
            name='clinical_evaluation',
            options={'verbose_name': 'Clinical Evaluation', 'verbose_name_plural': 'Clinical Evaluations'},
        ),
        migrations.AlterModelOptions(
            name='clinicalevent',
            options={'verbose_name': 'Clinical Event', 'verbose_name_plural': 'Clinical Events'},
        ),
        migrations.AlterModelOptions(
            name='deviceimplant',
            options={'verbose_name': 'Device implant', 'verbose_name_plural': 'Device implants'},
        ),
        migrations.AlterModelOptions(
            name='deviceinstance',
            options={'verbose_name': 'Device instance', 'verbose_name_plural': 'Device instances'},
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={'verbose_name': 'Device Type', 'verbose_name_plural': 'Device Types'},
        ),
        migrations.AlterModelOptions(
            name='ecg',
            options={'verbose_name': 'ECG', 'verbose_name_plural': 'ECGs'},
        ),
        migrations.AlterModelOptions(
            name='echo',
            options={'verbose_name': 'Ecography', 'verbose_name_plural': 'Ecography'},
        ),
        migrations.AlterModelOptions(
            name='flecainide_test',
            options={'verbose_name': 'Flecainide test', 'verbose_name_plural': 'Flecainide tests'},
        ),
        migrations.AlterModelOptions(
            name='genetic_profile',
            options={'verbose_name': 'Genetic profile', 'verbose_name_plural': 'Genetic profiles'},
        ),
        migrations.AlterModelOptions(
            name='genetic_sample',
            options={'verbose_name': 'Genetic sample', 'verbose_name_plural': 'Genetic samples'},
        ),
        migrations.AlterModelOptions(
            name='genetic_status',
            options={'verbose_name': 'Genetic status', 'verbose_name_plural': 'Genetic status'},
        ),
        migrations.AlterModelOptions(
            name='genetic_test',
            options={'verbose_name': 'Genetic test', 'verbose_name_plural': 'Genetic tests'},
        ),
        migrations.AlterModelOptions(
            name='late_potentials',
            options={'verbose_name': 'Late potential', 'verbose_name_plural': 'Late potentials'},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'permissions': [('access_sensible_info', 'Can view patient sensible info')], 'verbose_name': 'Patient Profile', 'verbose_name_plural': 'Patient Profiles'},
        ),
        migrations.AlterModelOptions(
            name='researchanalysis',
            options={'verbose_name': 'Omics Analysis', 'verbose_name_plural': 'Omics Analyses'},
        ),
        migrations.AlterModelOptions(
            name='riskfactors',
            options={'ordering': ['name'], 'verbose_name': 'Risk factor', 'verbose_name_plural': 'Risk factors'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': 'Sample', 'verbose_name_plural': 'Samples'},
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='cardioref_id',
            field=models.PositiveIntegerField(blank=True, default=''),
        ),
    ]
