# Generated by Django 5.1.6 on 2025-04-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0002_clinical_evaluation_comorbidities'),
        ('kokoro', '0004_rename_device_implant_deviceimplant_and_more'),
    ]

    operations = [
    ]
