# Generated by Django 5.1.6 on 2025-05-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0004_rename_consent_date_genetic_test_consent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='genetic_test',
            name='card_subcategory',
            field=models.CharField(choices=[('HMC', 'HMC'), ('ARVD', 'ARVD'), ('NCM', 'NCM'), ('CMIO DILATED', 'CMIO DILATED'), ('Stuctural', 'Structural'), ('Amilo', 'Amilo'), ('Osi', 'Osi'), ('Fabry', 'Fabry'), ('ARVC', 'ARVC'), ('Guch', 'Guch')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='chan_subcategory',
            field=models.CharField(choices=[('LQTS', 'LQTS'), ('ERS', 'ERS'), ('JWS', 'JWS'), ('Gitelman', 'Gitelman'), ('WPW', 'WPW'), ('BAV', 'BAV'), ('BBB', 'BBB'), ('CPVT', 'CPVT'), ('AF', 'AF')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='coll_subcategory',
            field=models.CharField(choices=[('Factor II', 'MFactor II'), ('Factor V', 'Factor V'), ('Thrombophilia', 'Thrombophilia'), ('MTHFR', 'MTHFR'), ('Hemophilia', 'Hemophilia'), ('Van Willebrandt', 'Van Willebrandt')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='dys_subcategory',
            field=models.CharField(choices=[('Noonan', 'Noonan'), ('Turner', 'Turner'), ('Klinefelter', 'Klinefelter')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='metabolic_subcategory',
            field=models.CharField(choices=[('Diabetes', 'Diabetes'), ('Mody', 'Mody'), ('Dislipidemia', 'Dislipidemia'), ('Metal accumulation', 'Metal accumulation'), ('Alagille', 'Alagille'), ('Gaucher', 'Gaucher'), ('Pompe', 'Pompe')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='neuro_subcategory',
            field=models.CharField(choices=[('Steinert', 'Steinert'), ('Ataxia', 'Ataxia'), ('Huntington', 'Huntington'), ('Scapulus humeral', 'Scapulus humeral'), ('Epilepsy', 'Epilepsy'), ('Charcot-Marie Tooth', 'Charcot-Marie Tooth'), ('LGMD', 'LGMD')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='onco_subcategory',
            field=models.CharField(choices=[('Breast', 'Breast'), ('Pancreas', 'Pancreas'), ('Ovary', 'Ovary'), ('Colon', 'Metal accumulation'), ('Thyroid', 'Thyroid'), ('NF1', 'NF1'), ('Melanoma', 'Melanoma')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='genetic_test',
            name='test_category',
            field=models.CharField(choices=[('Oncology', 'Oncology'), ('Channellopathies / Arrhythmias', 'Channellopathies / Arrhythmias'), ('Cardiomiopathies', 'Cardiomiopathies'), ('Neuromuscolar dystrophies', 'Nd'), ('Collagenopathies', 'Collagenopathies'), ('Coagulopathies', 'Coagulopathies'), ('Syndromes / Dysmorphisms', 'Syndromes / Dysmorphisms'), ('Metabolic', 'Metabolic'), ('Screening', 'Screening'), ('Breast K', 'Breast K'), ('Nephropathy', 'Nephropathy'), ('Neuropathy', 'Neuropathy'), ('Hematopathy', 'Hematopathy')], default='', max_length=100),
        ),
    ]
