# Generated by Django 5.1.6 on 2025-05-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0004_alter_ablation_options_alter_adrenaline_test_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='cardioref_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
