# Generated by Django 5.1.6 on 2025-05-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0005_genetic_test_card_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genetic_test',
            name='processing_type',
            field=models.CharField(choices=[('OSR', 'OSR'), ('IMTC', 'IMTC')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='test_result',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Not concluded', 'Not concluded')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='genetic_test',
            name='chan_subcategory',
            field=models.CharField(choices=[('LQTS', 'LQTS'), ('ERS', 'ERS'), ('JWS', 'JWS'), ('Gitelman', 'Gitelman'), ('WPW', 'WPW'), ('BAV', 'BAV'), ('BBB', 'BBB'), ('CPVT', 'CPVT'), ('AF', 'AF'), ('BrS', 'BrS')], default='', max_length=100),
        ),
    ]
