# Generated by Django 5.1.6 on 2025-05-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0006_genetic_test_processing_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Gene',
                'verbose_name_plural': 'Genes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Mutation',
                'verbose_name_plural': 'Mutations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='genes',
            field=models.ManyToManyField(blank=True, help_text='Gene of this test.', related_name='genes', to='kokoro.gene'),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='mutations',
            field=models.ManyToManyField(blank=True, help_text='Mutation of this test.', related_name='mutations', to='kokoro.mutation'),
        ),
    ]
