# Generated by Django 5.1.6 on 2025-05-06 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0007_therapy_coronaryintervention_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_name', models.CharField(blank=True, help_text='Analysis name', max_length=250)),
                ('type', models.CharField(choices=[('WGS', 'Whole Genome Sequencing'), ('WES', 'Whole Exome Sequencing'), ('RNAseq', 'RNA sequencing'), ('PRO', 'Proteomics (Mass Spectrometry)')], help_text='Type of omics analysis performed', max_length=10)),
                ('date_performed', models.DateField(auto_now_add=True)),
                ('result_files', models.JSONField(blank=True, help_text='Paths or identifiers for result files', null=True)),
                ('samples', models.ManyToManyField(help_text='Samples used in this analysis', related_name='analyses', to='kokoro.sample')),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
            },
        ),
    ]
