# Generated by Django 5.1.6 on 2025-05-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0007_gene_mutation_genetic_test_genes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genetic_test',
            name='zygosity',
            field=models.CharField(choices=[('HZ', 'HZ'), ('OZ', 'OZ'), ('HA', 'HA')], default='', max_length=100),
        ),
    ]
