# Generated by Django 5.1.6 on 2025-05-07 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0008_researchanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_studies', to='kokoro.patientprofile')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_participants', to='kokoro.study')),
            ],
            options={
                'ordering': ['-enrollment_date'],
                'unique_together': {('patient', 'study')},
            },
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='studies',
            field=models.ManyToManyField(blank=True, help_text='Which studies this patient is enrolled in', related_name='participants', through='kokoro.PatientStudy', to='kokoro.study'),
        ),
    ]
