# Generated by Django 5.1.6 on 2025-05-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0008_genetic_test_zygosity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='classes',
            field=models.ManyToManyField(blank=True, help_text='Class of this test.', related_name='classes', to='kokoro.class'),
        ),
    ]
