# Generated by Django 5.1.6 on 2025-05-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0009_study_patientstudy_patientprofile_studies'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='allergies',
            field=models.ManyToManyField(blank=True, help_text="Patient's allergies", related_name='patient_allergies', to='kokoro.therapy'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='therapies',
            field=models.ManyToManyField(blank=True, help_text='Therapies this patient is on.', related_name='patients_therapies', to='kokoro.therapy'),
        ),
    ]
