# Generated by Django 5.1.6 on 2025-05-16 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0009_class_genetic_test_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='genetic_test',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='genetic_status',
            name='brs_family_members',
        ),
        migrations.RemoveField(
            model_name='genetic_status',
            name='cardiomiopathy_family_members',
        ),
        migrations.RemoveField(
            model_name='genetic_status',
            name='er_family_members',
        ),
        migrations.RemoveField(
            model_name='genetic_status',
            name='family_brs',
        ),
        migrations.RemoveField(
            model_name='genetic_status',
            name='family_cardiomiopathy',
        ),
        migrations.RemoveField(
            model_name='genetic_status',
            name='family_er',
        ),
        migrations.RemoveField(
            model_name='genetic_status',
            name='family_lqts',
        ),
        migrations.RemoveField(
            model_name='genetic_status',
            name='lqts_family_members',
        ),
        migrations.RemoveField(
            model_name='genetic_status',
            name='sd_family_degree',
        ),
        migrations.RemoveField(
            model_name='genetic_status',
            name='sd_family_members',
        ),
        migrations.RemoveField(
            model_name='genetic_test',
            name='mutations',
        ),
        migrations.RemoveField(
            model_name='genetic_test',
            name='processing_type',
        ),
        migrations.RemoveField(
            model_name='genetic_test',
            name='test_result',
        ),
        migrations.AddField(
            model_name='genetic_status',
            name='cardio_fenotypes',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_status',
            name='children',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genetic_status',
            name='familiarityType',
            field=models.CharField(choices=[('SD', 'SD'), ('Cardiopathy', 'Cardiopathy'), ('Other pathologies', 'Other pathologies')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_status',
            name='family_degree',
            field=models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Grand-father', 'Grand-father'), ('Grand-mother', 'Grand-mother')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_status',
            name='family_members',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genetic_status',
            name='pato_fenotypes',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_status',
            name='proband_familiarity',
            field=models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Grand-father', 'Grand-father'), ('Grand-mother', 'Grand-mother')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='ACMG',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='Mutunatest_result',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Not concluded', 'Not concluded')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='NGStest_result',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Not concluded', 'Not concluded')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='Sangen_result',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Not concluded', 'Not concluded')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='aliquota',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='corsa_NGS',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='corsa_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='cromo_anomality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='eredity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='gene_type',
            field=models.CharField(choices=[('Clinical', 'Clinical'), ('Incidental', 'Incidental')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='processingType',
            field=models.CharField(choices=[('OSR', 'OSR'), ('IMTC', 'IMTC')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='report_data',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='reported',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='sampleType',
            field=models.CharField(choices=[('blood', 'blood'), ('DNA', 'DNA')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='sangen',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='testType',
            field=models.CharField(choices=[('NGS', 'NGS'), ('Mutuna', 'Mutuna')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='var_c',
            field=models.ManyToManyField(blank=True, help_text='v1c', related_name='v1c', to='kokoro.mutation'),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='var_p',
            field=models.ManyToManyField(blank=True, help_text='v1p', related_name='v1p', to='kokoro.mutation'),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='editing_doctor',
            field=models.ManyToManyField(blank=True, related_name='Editing_doctor', to='kokoro.doctors'),
        ),
        migrations.AddField(
            model_name='genetic_test',
            name='reporting_doctor',
            field=models.ManyToManyField(blank=True, related_name='Reporting_doctor', to='kokoro.doctors'),
        ),
        migrations.CreateModel(
            name='Genetic_sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('blood_sample_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kokoro.patientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
