# Generated by Django 5.1.6 on 2025-06-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0009_alter_genetic_test_ngstest_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genetic_test',
            name='cromo_anomality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='genetic_test',
            name='eredity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
