# Generated by Django 5.1.6 on 2025-05-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0002_clinicalevent'),
        ('kokoro', '0010_doctors_remove_genetic_test_classes_and_more'),
    ]

    operations = [
    ]
