# Generated by Django 5.1.6 on 2025-07-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0010_alter_genetic_test_cromo_anomality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecg',
            name='ecg_file',
            field=models.FileField(blank=True, null=True, upload_to='ecg_data/'),
        ),
    ]
