from django.urls import path
from django.views.generic import TemplateView
from .views import (PatientProfileCreateView, PatientProfileUpdateView, LatePotentialCreateView,
					LatePotentialUpdateView, StudyCreateView, StudyUpdateView,
					ValveInterventionCreateView, ValveInterventionUpdateView, SampleCreateView,
					SampleUpdateView, RMN_TC_PHCreateView, RMN_TC_PHUpdateView,
					Genetic_testCreateView, Genetic_testUpdateView, Genetic_statusCreateView,
					Genetic_statusUpdateView, Genetic_profileCreateView, Genetic_profileUpdateView,
					Flecainide_testCreateView, Flecainide_testUpdateView, ECHOCreateView,
					ECHOUpdateView, ECGCreateView, ECGUpdateView,
					EP_studyCreateView, EP_studyUpdateView, DeviceInstanceCreateView,
					DeviceInstanceUpdateView, DeviceImplantCreateView, DeviceImplantUpdateView,
					DeviceEventCreateView, DeviceEventUpdateView, CoronaryInterventionCreateView,
					CoronaryInterventionUpdateView, ClinicalEventCreateView, ClinicalEventUpdateView,
					Clinical_evaluationCreateView, Clinical_evaluationUpdateView, Ajmaline_testCreateView,
					Ajmaline_testUpdateView, Ajmaline_testCreateView, Ajmaline_testUpdateView,
					Adrenaline_testCreateView, Adrenaline_testUpdateView, AblationCreateView,
					AblationUpdateView,
				)

app_name = 'submissions'

urlpatterns = [
	path('valveintervention/add/', ValveInterventionCreateView.as_view(), name='add_valveintervention'),
	path('valveintervention/edit/<uuid:pk>/', ValveInterventionUpdateView.as_view(), name='edit_valveintervention'),
	path('sample/add/', SampleCreateView.as_view(), name='add_sample'),
	path('sample/edit/<uuid:pk>/', SampleUpdateView.as_view(), name='edit_sample'),
	path('rmn_tc_ph/add/', RMN_TC_PHCreateView.as_view(), name='add_rmn_tc_ph'),
	path('rmn_tc_ph/edit/<uuid:pk>/', RMN_TC_PHUpdateView.as_view(), name='edit_rmn_tc_ph'),
	path('genetic_test/add/', Genetic_testCreateView.as_view(), name='add_genetic_test'),
	path('genetic_test/edit/<uuid:pk>/', Genetic_testUpdateView.as_view(), name='edit_genetic_test'),
	path('genetic_status/add/', Genetic_statusCreateView.as_view(), name='add_genetic_status'),
	path('genetic_status/edit/<uuid:pk>/', Genetic_statusUpdateView.as_view(), name='edit_genetic_status'),
	path('genetic_profile/add/', Genetic_profileCreateView.as_view(), name='add_genetic_profile'),
	path('genetic_profile/edit/<uuid:pk>/', Genetic_profileUpdateView.as_view(), name='edit_genetic_profile'),
	path('flecainide_test/add/', Flecainide_testCreateView.as_view(), name='add_flecainide_test'),
	path('flecainide_test/edit/<uuid:pk>/', Flecainide_testUpdateView.as_view(), name='edit_flecainide_test'),
	path('echo/add/', ECHOCreateView.as_view(), name='add_echo'),
	path('echo/edit/<uuid:pk>/', ECHOUpdateView.as_view(), name='edit_echo'),
	path('ecg/add/', ECGCreateView.as_view(), name='add_ecg'),
	path('ecg/edit/<uuid:pk>/', ECGUpdateView.as_view(), name='edit_ecg'),
	path('ep_study/add/', EP_studyCreateView.as_view(), name='add_ep_study'),
	path('ep_study/edit/<uuid:pk>/', EP_studyUpdateView.as_view(), name='edit_ep_study'),
	path('deviceinstance/add/', DeviceInstanceCreateView.as_view(), name='add_deviceinstance'),
	path('deviceinstance/edit/<uuid:pk>/', DeviceInstanceUpdateView.as_view(), name='edit_deviceinstance'),
	path('deviceimplant/add/', DeviceImplantCreateView.as_view(), name='add_deviceimplant'),
	path('deviceimplant/edit/<uuid:pk>/', DeviceImplantUpdateView.as_view(), name='edit_deviceimplant'),
	path('deviceevent/add/', DeviceEventUpdateView.as_view(), name='add_deviceevent'),
	path('deviceevent/edit/<uuid:pk>/', DeviceEventUpdateView.as_view(), name='edit_deviceevent'),
	path('coronaryintervention/add/', CoronaryInterventionCreateView.as_view(), name='add_coronaryintervention'),
	path('coronaryintervention/edit/<uuid:pk>/', CoronaryInterventionUpdateView.as_view(), name='edit_coronaryintervention'),
	path('clinicalevent/add/', ClinicalEventCreateView.as_view(), name='add_clinicalevent'),
	path('clinicalevent/edit/<uuid:pk>/', ClinicalEventUpdateView.as_view(), name='edit_clinicalevent'),
	path('clinical_evaluation/add/', Clinical_evaluationCreateView.as_view(), name='add_clinical_evaluation'),
	path('clinical_evaluation/edit/<uuid:pk>/', Clinical_evaluationUpdateView.as_view(), name='edit_clinical_evaluation'),
	path('ajmaline_test/add/', Ajmaline_testCreateView.as_view(), name='add_ajmaline_test'),
	path('ajmaline_test/edit/<uuid:pk>/', Ajmaline_testUpdateView.as_view(), name='edit_ajmaline_test'),
	path('adrenaline_test/add/', Adrenaline_testCreateView.as_view(), name='add_adrenaline_test'),
	path('adrenaline_test/edit/<uuid:pk>/', Adrenaline_testUpdateView.as_view(), name='edit_adrenaline_test'),
	path('ablation/add/', AblationCreateView.as_view(), name='add_ablation'),
	path('ablation/edit/<uuid:pk>/', AblationUpdateView.as_view(), name='edit_ablation'),
	path('study/add/', StudyCreateView.as_view(), name='add_study'),
	path('study/edit/<uuid:pk>/', StudyUpdateView.as_view(), name='edit_study'),
	path('latepotential/add/', LatePotentialCreateView.as_view(), name='add_latepotential'),
	path('latepotential/edit/<uuid:pk>/', LatePotentialUpdateView.as_view(), name='edit_latepotential'),
	path('patientprofile/add/', PatientProfileCreateView.as_view(), name='add_patientprofile'),
	path('patientprofile/edit/<uuid:pk>/', PatientProfileUpdateView.as_view(), name='edit_patientprofile'),
	# Optional success page after submission
	path('success/', TemplateView.as_view(
		template_name='submissions/success.html'
	), name='submission_success'),  
]