# Generated by Django 5.1.6 on 2025-03-06 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('nation', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('province', models.CharField(blank=True, default='', max_length=100)),
                ('cardioref_id', models.CharField(blank=True, default='', max_length=100)),
                ('patient_type', models.CharField(blank=True, choices=[('P', 'Proband'), ('R', 'Relative')], default='', max_length=1)),
                ('fin', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'permissions': [('access_sensible_info', 'Can view patient sensible info')],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('collection_date', models.DateField()),
                ('storage_temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('freezer_location', models.CharField(blank=True, help_text='Storage freezer/box location', max_length=100)),
                ('initial_volume_ml', models.FloatField(help_text='Initial volume in milliliters')),
                ('remaining_volume_ml', models.FloatField(blank=True, help_text='Remaining volume in milliliters', null=True)),
                ('status', models.CharField(choices=[('ST', 'Stored'), ('IN', 'In Use'), ('EX', 'Exhausted'), ('CO', 'Contaminated'), ('DI', 'Disposed'), ('RT', 'Returned')], default='ST', max_length=2)),
                ('quality', models.CharField(choices=[('EX', 'Excellent'), ('GD', 'Good'), ('FR', 'Fair'), ('PR', 'Poor')], default='GD', max_length=2)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('WGS', 'Whole Genome Sequencing'), ('WES', 'Whole Exome Sequencing'), ('PRO', 'Proteomics (Mass Spectrometry)')], help_text='Type of omics analysis performed', max_length=10)),
                ('date_performed', models.DateField(auto_now_add=True)),
                ('result_files', models.JSONField(blank=True, help_text='Paths or identifiers for result files', null=True)),
                ('performed_by', models.ForeignKey(help_text='User who performed the analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('samples', models.ManyToManyField(help_text='Samples used in this analysis', related_name='analyses', to='patients.sample')),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
            },
        ),
    ]
