# Generated by Django 5.1.6 on 2025-02-19 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('nation', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('patient_type', models.CharField(choices=[('P', 'Proband'), ('R', 'Relative')], max_length=1)),
                ('fin', models.PositiveIntegerField()),
            ],
        ),
    ]
