# Generated by Django 5.1.6 on 2025-03-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='analysis_name',
            field=models.CharField(blank=True, help_text='Analysis name', max_length=250),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='type',
            field=models.CharField(choices=[('WGS', 'Whole Genome Sequencing'), ('WES', 'Whole Exome Sequencing'), ('RNAseq', 'RNA sequencing'), ('PRO', 'Proteomics (Mass Spectrometry)')], help_text='Type of omics analysis performed', max_length=10),
        ),
    ]
