# Generated by Django 5.1.6 on 2025-02-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('access_sensible_info', 'Can view patient sensible info')]},
        ),
    ]
