# Generated by Django 5.1.6 on 2025-02-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cardioref_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fin',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('P', 'Proband'), ('R', 'Relative')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
