# Generated by Django 5.1.6 on 2025-02-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_cardioref_id_alter_patient_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
